# Generated by Django 6.0.7 on 2026-08-03 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.teachers'),
        ),
    ]
