# Generated by Django 6.0.7 on 2026-08-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.teachers'),
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(to='students.courses'),
        ),
    ]
