# Generated by Django 6.0.7 on 2026-08-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_courses_remove_students_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
    ]
