# Generated by Django 6.0.7 on 2026-08-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_students_course_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(default='Pyhton', max_length=67),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.teachers'),
        ),
        migrations.CreateModel(
            name='studentdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Certificate', 'Certificate'), ('Assignment', 'Assignment'), ('Marksheet', 'Marksheet'), ('Notes', 'Notes'), ('Other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.students')),
            ],
        ),
    ]
