# Generated by Django 6.0.7 on 2026-08-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_students_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='subject',
            new_name='course',
        ),
    ]
