# Generated by Django 6.0.7 on 2026-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_subject_teachers_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
