# Generated by Django 6.0.7 on 2026-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(db_index=True, max_length=67),
        ),
    ]
