# Generated by Django 6.0.7 on 2026-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.FileField(upload_to='students/'),
        ),
    ]
