# Generated by Django 6.0.7 on 2026-08-31 05:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_students_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='student_documents/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to='students/'),
        ),
    ]
